FROM node:latest
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 8080
ENV PORT=8080

ARG CLIENT_ID
ARG CLIENT_SECRET
ARG REDIRECT_URI
ARG MYDOMAIN
ENV CLIENT_ID="${CLIENT_ID}"
ENV CLIENT_SECRET="${CLIENT_SECRET}"
ENV REDIRECT_URI="${REDIRECT_URI}"
ENV MYDOMAIN="${MYDOMAIN}"

CMD [ "npm", "run", "start" ]
